/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequestDto
 */
export interface AuthRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AuthRequestDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRequestDto
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthRequestDto interface.
 */
export function instanceOfAuthRequestDto(value: object): value is AuthRequestDto {
    return true;
}

export function AuthRequestDtoFromJSON(json: any): AuthRequestDto {
    return AuthRequestDtoFromJSONTyped(json, false);
}

export function AuthRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthRequestDtoToJSON(json: any): AuthRequestDto {
    return AuthRequestDtoToJSONTyped(json, false);
}

export function AuthRequestDtoToJSONTyped(value?: AuthRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

