/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterRequestDto
 */
export interface RegisterRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    password?: string;
}

/**
 * Check if a given object implements the RegisterRequestDto interface.
 */
export function instanceOfRegisterRequestDto(value: object): value is RegisterRequestDto {
    return true;
}

export function RegisterRequestDtoFromJSON(json: any): RegisterRequestDto {
    return RegisterRequestDtoFromJSONTyped(json, false);
}

export function RegisterRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function RegisterRequestDtoToJSON(json: any): RegisterRequestDto {
    return RegisterRequestDtoToJSONTyped(json, false);
}

export function RegisterRequestDtoToJSONTyped(value?: RegisterRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
    };
}

