/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminDto
 */
export interface AdminDto {
    /**
     * 
     * @type {string}
     * @memberof AdminDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminDto
     */
    password?: string;
}

/**
 * Check if a given object implements the AdminDto interface.
 */
export function instanceOfAdminDto(value: object): value is AdminDto {
    return true;
}

export function AdminDtoFromJSON(json: any): AdminDto {
    return AdminDtoFromJSONTyped(json, false);
}

export function AdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AdminDtoToJSON(json: any): AdminDto {
    return AdminDtoToJSONTyped(json, false);
}

export function AdminDtoToJSONTyped(value?: AdminDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

