/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyDto
 */
export interface CompanyDto {
    /**
     * 
     * @type {number}
     * @memberof CompanyDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    joinCode?: string;
}

/**
 * Check if a given object implements the CompanyDto interface.
 */
export function instanceOfCompanyDto(value: object): value is CompanyDto {
    return true;
}

export function CompanyDtoFromJSON(json: any): CompanyDto {
    return CompanyDtoFromJSONTyped(json, false);
}

export function CompanyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'joinCode': json['joinCode'] == null ? undefined : json['joinCode'],
    };
}

export function CompanyDtoToJSON(json: any): CompanyDto {
    return CompanyDtoToJSONTyped(json, false);
}

export function CompanyDtoToJSONTyped(value?: CompanyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'domain': value['domain'],
        'joinCode': value['joinCode'],
    };
}

