/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the InviteRequest interface.
 */
export function instanceOfInviteRequest(value) {
    return true;
}
export function InviteRequestFromJSON(json) {
    return InviteRequestFromJSONTyped(json, false);
}
export function InviteRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}
export function InviteRequestToJSON(json) {
    return InviteRequestToJSONTyped(json, false);
}
export function InviteRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'email': value['email'],
        'role': value['role'],
    };
}
