/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteRequest
 */
export interface InviteRequest {
    /**
     * 
     * @type {string}
     * @memberof InviteRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof InviteRequest
     */
    role?: string;
}

/**
 * Check if a given object implements the InviteRequest interface.
 */
export function instanceOfInviteRequest(value: object): value is InviteRequest {
    return true;
}

export function InviteRequestFromJSON(json: any): InviteRequest {
    return InviteRequestFromJSONTyped(json, false);
}

export function InviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function InviteRequestToJSON(json: any): InviteRequest {
    return InviteRequestToJSONTyped(json, false);
}

export function InviteRequestToJSONTyped(value?: InviteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
    };
}

