/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './user';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './user';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {number}
     * @memberof Notification
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    type?: NotificationTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt?: Date;
    /**
     * 
     * @type {User}
     * @memberof Notification
     */
    recipient?: User;
    /**
     * 
     * @type {number}
     * @memberof Notification
     */
    relatedEntityId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    read?: boolean;
}


/**
 * @export
 */
export const NotificationTypeEnum = {
    TaskAssigned: 'TASK_ASSIGNED',
    TaskUpdated: 'TASK_UPDATED',
    CommentAdded: 'COMMENT_ADDED',
    ProjectAssigned: 'PROJECT_ASSIGNED',
    ProjectUpdated: 'PROJECT_UPDATED'
} as const;
export type NotificationTypeEnum = typeof NotificationTypeEnum[keyof typeof NotificationTypeEnum];


/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'recipient': json['recipient'] == null ? undefined : UserFromJSON(json['recipient']),
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'read': json['read'] == null ? undefined : json['read'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
        'type': value['type'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'recipient': UserToJSON(value['recipient']),
        'relatedEntityId': value['relatedEntityId'],
        'read': value['read'],
    };
}

