/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDto } from './project-dto';
import {
    ProjectDtoFromJSON,
    ProjectDtoFromJSONTyped,
    ProjectDtoToJSON,
    ProjectDtoToJSONTyped,
} from './project-dto';

/**
 * 
 * @export
 * @interface TaskDto
 */
export interface TaskDto {
    /**
     * 
     * @type {number}
     * @memberof TaskDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskDto
     */
    dueDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    status?: TaskDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    priority?: TaskDtoPriorityEnum;
    /**
     * 
     * @type {ProjectDto}
     * @memberof TaskDto
     */
    project?: ProjectDto;
    /**
     * 
     * @type {number}
     * @memberof TaskDto
     */
    assigneeId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskDto
     */
    creatorId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskDto
     */
    companyId?: number;
}


/**
 * @export
 */
export const TaskDtoStatusEnum = {
    ToDo: 'TO_DO',
    InProgress: 'IN_PROGRESS',
    Review: 'REVIEW',
    Done: 'DONE'
} as const;
export type TaskDtoStatusEnum = typeof TaskDtoStatusEnum[keyof typeof TaskDtoStatusEnum];

/**
 * @export
 */
export const TaskDtoPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type TaskDtoPriorityEnum = typeof TaskDtoPriorityEnum[keyof typeof TaskDtoPriorityEnum];


/**
 * Check if a given object implements the TaskDto interface.
 */
export function instanceOfTaskDto(value: object): value is TaskDto {
    return true;
}

export function TaskDtoFromJSON(json: any): TaskDto {
    return TaskDtoFromJSONTyped(json, false);
}

export function TaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
        'status': json['status'] == null ? undefined : json['status'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'project': json['project'] == null ? undefined : ProjectDtoFromJSON(json['project']),
        'assigneeId': json['assigneeId'] == null ? undefined : json['assigneeId'],
        'creatorId': json['creatorId'] == null ? undefined : json['creatorId'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
    };
}

export function TaskDtoToJSON(json: any): TaskDto {
    return TaskDtoToJSONTyped(json, false);
}

export function TaskDtoToJSONTyped(value?: TaskDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'dueDate': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
        'status': value['status'],
        'priority': value['priority'],
        'project': ProjectDtoToJSON(value['project']),
        'assigneeId': value['assigneeId'],
        'creatorId': value['creatorId'],
        'companyId': value['companyId'],
    };
}

