/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TeamDto interface.
 */
export function instanceOfTeamDto(value) {
    return true;
}
export function TeamDtoFromJSON(json) {
    return TeamDtoFromJSONTyped(json, false);
}
export function TeamDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'members': json['members'] == null ? undefined : new Set(json['members']),
    };
}
export function TeamDtoToJSON(json) {
    return TeamDtoToJSONTyped(json, false);
}
export function TeamDtoToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'members': value['members'] == null ? undefined : Array.from(value['members']),
    };
}
