/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadUserCSVRequest
 */
export interface UploadUserCSVRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UploadUserCSVRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the UploadUserCSVRequest interface.
 */
export function instanceOfUploadUserCSVRequest(value: object): value is UploadUserCSVRequest {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function UploadUserCSVRequestFromJSON(json: any): UploadUserCSVRequest {
    return UploadUserCSVRequestFromJSONTyped(json, false);
}

export function UploadUserCSVRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUserCSVRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function UploadUserCSVRequestToJSON(json: any): UploadUserCSVRequest {
    return UploadUserCSVRequestToJSONTyped(json, false);
}

export function UploadUserCSVRequestToJSONTyped(value?: UploadUserCSVRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

