/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleFromJSON, RoleToJSON, } from './role';
/**
 * Check if a given object implements the UserDto interface.
 */
export function instanceOfUserDto(value) {
    return true;
}
export function UserDtoFromJSON(json) {
    return UserDtoFromJSONTyped(json, false);
}
export function UserDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'roles': json['roles'] == null ? undefined : (new Set(json['roles'].map(RoleFromJSON))),
    };
}
export function UserDtoToJSON(json) {
    return UserDtoToJSONTyped(json, false);
}
export function UserDtoToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'roles': value['roles'] == null ? undefined : (Array.from(value['roles']).map(RoleToJSON)),
    };
}
