/* tslint:disable */
/* eslint-disable */
/**
 * Project Management Tool API
 * API documentation for Project Management Tool
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyDto } from './company-dto';
import {
    CompanyDtoFromJSON,
    CompanyDtoFromJSONTyped,
    CompanyDtoToJSON,
    CompanyDtoToJSONTyped,
} from './company-dto';

/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    email?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof UserDto
     */
    roles?: Set<string>;
    /**
     * 
     * @type {CompanyDto}
     * @memberof UserDto
     */
    companyDto?: CompanyDto;
    /**
     * 
     * @type {Date}
     * @memberof UserDto
     */
    lastActive?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    profileImageUrl?: string;
}

/**
 * Check if a given object implements the UserDto interface.
 */
export function instanceOfUserDto(value: object): value is UserDto {
    return true;
}

export function UserDtoFromJSON(json: any): UserDto {
    return UserDtoFromJSONTyped(json, false);
}

export function UserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'roles': json['roles'] == null ? undefined : new Set(json['roles']),
        'companyDto': json['companyDto'] == null ? undefined : CompanyDtoFromJSON(json['companyDto']),
        'lastActive': json['lastActive'] == null ? undefined : (new Date(json['lastActive'])),
        'profileImageUrl': json['profileImageUrl'] == null ? undefined : json['profileImageUrl'],
    };
}

export function UserDtoToJSON(json: any): UserDto {
    return UserDtoToJSONTyped(json, false);
}

export function UserDtoToJSONTyped(value?: UserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'roles': value['roles'] == null ? undefined : Array.from(value['roles'] as Set<any>),
        'companyDto': CompanyDtoToJSON(value['companyDto']),
        'lastActive': value['lastActive'] == null ? value['lastActive'] : value['lastActive'].toISOString().substring(0,10),
        'profileImageUrl': value['profileImageUrl'],
    };
}

